name: Build and Deploy PTUDDN_t6

on:
  push:
    branches:
      - main
      - master

jobs:
  build-deploy:
    name: Build and Deploy PTUDDN_t6
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Unit tests
        run: mvn -B test --file pom.xml

      - name: Build the app
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Build the Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ptuddn_t6:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push the Docker image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ptuddn_t6:latest